services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: phy-sound-checker
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
    tty: true
    stdin_open: true